### ISSUE TITLE
Inconsistent database accessor behavior

### ISSUE THREAD

**Issue by ppacher** [safing/portbase#75]
When trying to store a struct with `json:"someThing"` field tags in the database the behavior of the accessor function used during query processing is inconsistent as the actual JSON blob (and thus JSON field accessor) has a different key than the struct based accessor (which uses the Field name as it is).

Consider the following record type:

```go
type Foo struct {
    record.Base
    Name string `json:"name"`
}
``` 

A query that searches for `name == "foo"` must look like this to work as expected:

```go
where := query.Or(
    query.Where("name", query.SameAs, "foo"), // required for the JSON value accessor
    query.Where("Name", query.SameAs, "foo"), // required for the Struct field accessor
)
```

This adds considerably more complexity when writing database queries.

**Proposed solutions**

1. **Drop the different accessor functions and replace them by a common one.**
    AFAIK the different accessor functions have been added for performance reasons as it's not required to decode the JSON of each database record. We can either check if this really poses a performance issue (or if it has been assumed to be one) and if, check if implementations like https://github.com/segmentio/encoding would reduce the overhead enough to perform JSON decoding on every record.
    We might also consider to keep the JSON accessor and marshal any already-parsed record back to JSON. Which one is better likely depends on cache size.

2. **Update the struct-based accessor to support JSON tags.**
    While being relatively simple to achieve, we add an additional dependency to JSON and will likely increase the burden of switching to some different encoding in the future.

**Comment by dhaavi** [comment]
This is a very good point. I see that this will need additional discussion about where we want to go with this system in the future.

For now, I think the best way to go is to not use any custom JSON name tags until we have this figured out.
